### ISSUE TITLE
[BUILD] 인프라 구축

### ISSUE THREAD

**Issue by cheon4050** [team-abcdedu/abcdedu-backend#13]
## 📝 개요
프로젝트에 사용하는 인프라 구축.

## ✅ TODO

- [x] AWS인프라 배포하기(ec2, s3, rds, elasticcache 등)
- [x] ci/cd구축

**Comment by S2uJeong** [comment]
안녕하세요 동천님! elasticcache은 어느 용도로 쓰실 예정일까요~? 궁금해서 여쭤봅니다!
